name: trigger-netlify-build | Main Branch

on:
  push:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.YOUR_BUILD_HOOK }}
